# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout:
          name: Checkout repo

      - run:
          name: Build
          command: gradle distZip

      - save_cache:
          name: Cache build
          paths:
            - build/distributions/nycfoodblog-1.0.0.zip
          key: v1-build-{{ .Revision }}
        
      - run:
          name: Test
          command: gradle test

  deploy:

    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/deploy

    steps:
      - restore_cache:
          name: Download build
          key: v1-build-{{ .Revision }}

      - run:
          name: Uncompress Build
          command: unzip ~/repo/build/distributions/nycfoodblog-1.0.0.zip

      - run:
          name: Stop service
          command: ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com "cd /home/ec2-user/nycfoodblog-1.0.0 && ./stop.sh"

      - run:
          name: Delete old bin
          command: ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com rm -rf /home/ec2-user/nycfoodblog-1.0.0/bin/*
      
      - run:
          name: Delete old lib
          command: ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com rm -rf /home/ec2-user/nycfoodblog-1.0.0/lib/*
      
      - run:
          name: Deploy new bin
          command: scp -o StrictHostKeyChecking=no -r nycfoodblog-1.0.0/bin/* ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com:~/nycfoodblog-1.0.0/bin/

      - run:
          name: Deploy new lib
          command: scp -o StrictHostKeyChecking=no -r nycfoodblog-1.0.0/lib/* ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com:~/nycfoodblog-1.0.0/lib/

      - run:
          name: Start service
          command: ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-210-44-111.compute-1.amazonaws.com "cd /home/ec2-user/nycfoodblog-1.0.0 && ./start.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

